version: '3.9'
services:
  db:
    image: mariadb
    container_name: db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ${DB_FILES_PATH}:/var/lib/mysql

  backend:
    build:
      dockerfile: Dockerfile
      context: backend
    command: >
      bash -c "python manage.py makemigrations && python manage.py runserver 0.0.0.0:8000"
    restart: always
    depends_on:
      - db

  frontend:
    build: frontend
    command: npm run build
    volumes:
      - html:/etc/project_frontend/dist
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - ./ssl:/etc/ssl/dimasik.sytes.net
      - html:/var/html
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
      - "443:443"

volumes:
  html: